import { GalleryImage, Image } from "../types/Image";

const isVite = import.meta.env.MODE !== undefined;
const baseUrl = `${isVite ? '/src' : ''}/gallery/`

const aboutImage: Image = {
  src: `${baseUrl}about.JPG`,
}

const charismaImages: GalleryImage[] = [
  {
    src: `${baseUrl}1.JPG`,
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: `${baseUrl}2.PNG`,
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: `${baseUrl}3.PNG`,
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: `${baseUrl}4.PNG`,
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: `${baseUrl}5.PNG`,
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },

  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/1.JPG",
    width: 524,
    height: 793,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/2.PNG",
    width: 610,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/3.PNG",
    width: 611,
    height: 920,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/4.PNG",
    width: 615,
    height: 919,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  {
    src: "src/images/charisma/5.PNG",
    width: 602,
    height: 915,
    title: "aaaaa",
    description: "After Rain (Jeshu John - designerspics.com)",
  },
  
];

export { charismaImages, aboutImage };
